# Generated by Django 6.0.5 on 2026-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Under Review'), ('confirmed', 'Confirmed'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
