# Generated by Django 6.0.5 on 2026-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='نسبة التخفيض % (0 = لا يوجد تخفيض)', max_digits=5),
        ),
    ]
